plugins {
    id 'net.neoforged.gradle.userdev'
    id 'java'
}

group = 'com.prisonplanet'
version = "${mod_version}"

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

minecraft {
    accessTransformers {
        file('src/main/resources/META-INF/accesstransformer.cfg')
    }
}

runs {
    client {
        workingDirectory project.file('run')
        systemProperty 'forge.logging.markers', 'REGISTRIES'
        systemProperty 'forge.logging.console.level', 'debug'
        programArguments '--username', 'Dev'
    }
    server {
        workingDirectory project.file('run')
        systemProperty 'forge.logging.markers', 'REGISTRIES'
        systemProperty 'forge.logging.console.level', 'debug'
    }
    data {
        workingDirectory project.file('run')
        systemProperty 'forge.logging.markers', 'REGISTRIES'
        systemProperty 'forge.logging.console.level', 'debug'
        programArguments '--mod', "${mod_id}", '--all',
                '--output', file('src/generated/resources/').getAbsolutePath(),
                '--existing', file('src/main/resources/').getAbsolutePath()
    }
}

sourceSets {
    main {
        resources {
            srcDir 'src/generated/resources'
        }
    }
}

dependencies {
    implementation "net.neoforged:neoforge:${neoforge_version}"
}

processResources {
    var replaceProperties = [
        mod_id      : mod_id,
        mod_version : mod_version,
        minecraft_version : minecraft_version,
        neoforge_version  : neoforge_version
    ]
    inputs.properties replaceProperties
    filesMatching('META-INF/neoforge.mods.toml') {
        expand replaceProperties
    }
}

repositories {
    maven { url = 'https://maven.neoforged.net/releases' }
}
